### ISSUE TITLE
请问方便提供数据库SQL吗

### ISSUE THREAD

**Issue by rainbowsky911** [sustly/blog_vue_server#10]
请问方便提供数据库SQL吗

**Comment by sustly** [comment]
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for blog
-- ----------------------------
DROP TABLE IF EXISTS `blog`;
CREATE TABLE `blog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content` longtext COMMENT '正文',
  `create_time` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL COMMENT '类别',
  `title` varchar(255) DEFAULT NULL,
  `create_user` varchar(64) DEFAULT NULL,
  `views` int(11) DEFAULT '0' COMMENT '浏览量',
  PRIMARY KEY (`id`),
  UNIQUE KEY `blog_id_uindex` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for blog_image
-- ----------------------------
DROP TABLE IF EXISTS `blog_image`;
CREATE TABLE `blog_image` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image_url` varchar(255) DEFAULT NULL,
  `blog_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `blog_image_id_uindex` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) NOT NULL,
  `password` varchar(64) NOT NULL,
  `create_time` varchar(30) DEFAULT NULL,
  `last_login_time` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id_uindex` (`id`),
  UNIQUE KEY `user_username_uindex` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
